"""Render and write Fortran SIGINI/UPOREP sources for 3D models.

Coordinate convention: Z = vertical upward, XY = horizontal plane.
Gravity acts in -Z.
"""

from __future__ import division, print_function

import os
import shutil

from geostatic_initializer_core_3d import interpolate_surface

FORTRAN_NAME = "initial_fields_generated_3d.for"
PYTHON_NAME = "generate_geostatic_initial_fields_3d.py"


def _d(value):
    return "%.12fD0" % float(value)


def _data_lines(name, values, formatter=_d):
    """Fixed-format Fortran DATA lines."""
    rendered = [formatter(value) for value in values]
    lines = ["      DATA %s /" % name]
    chunks = []
    current = []
    for value in rendered:
        candidate = current + [value]
        if current and len("     1 %s," % ",".join(candidate)) > 72:
            chunks.append(current)
            current = [value]
        else:
            current = candidate
        if len("     1 %s/" % value) > 72:
            raise ValueError("DATA item for %s exceeds fixed-format column 72" % name)
    if current:
        chunks.append(current)
    for index, chunk in enumerate(chunks):
        suffix = "/" if index + 1 == len(chunks) else ","
        lines.append("     1 %s%s" % (",".join(chunk), suffix))
    return lines


def _integer(value):
    return str(int(value))


def _character(value):
    return "'%s'" % str(value).upper().replace("'", "''")


def _flatten_triangles_3d(plan):
    """Flatten triangle data for all regions into flat arrays."""
    tlo_x, tlo_y, tlo_z = [], [], []  # lower triangles
    tup_x, tup_y, tup_z = [], [], []  # upper triangles
    nlo = []   # number of triangles per region (lower)
    nup = []   # number of triangles per region (upper)
    ilo = []   # start offset (1-based) per region (lower)
    iup = []   # start offset (1-based) per region (upper)

    for region in plan["regions"]:
        lo = region["lower_triangles"]
        up = region["upper_triangles"]

        ilo.append(len(tlo_x) // 3 + 1)  # offset in vertex-index space
        nlo.append(len(lo))
        for tri in lo:
            for p in tri:
                tlo_x.append(p[0])
                tlo_y.append(p[1])
                tlo_z.append(p[2])

        iup.append(len(tup_x) // 3 + 1)
        nup.append(len(up))
        for tri in up:
            for p in tri:
                tup_x.append(p[0])
                tup_y.append(p[1])
                tup_z.append(p[2])

    return (ilo, nlo, tlo_x, tlo_y, tlo_z,
            iup, nup, tup_x, tup_y, tup_z)


def _flatten_ground_3d(plan):
    """Flatten ground surface triangles."""
    gx, gy, gz = [], [], []
    for tri in plan["ground_triangles"]:
        for p in tri:
            gx.append(p[0])
            gy.append(p[1])
            gz.append(p[2])
    return gx, gy, gz


def render_fortran_3d(plan):
    """Generate Fortran SIGINI + UPOREP for 3D model."""
    regions = plan["regions"]
    nreg = len(regions)

    for region in regions:
        if len(str(region["instance"]).upper()) > 60:
            raise ValueError("instance name exceeds fixed-format safe limit of 60 characters")

    # Flatten triangle data
    (ilo, nlo, tlx, tly, tlz,
     iup, nup, tux, tuy, tuz) = _flatten_triangles_3d(plan)

    gx, gy, gz = _flatten_ground_3d(plan)

    ntri_l = len(tlx) // 3  # total lower triangles
    ntri_u = len(tux) // 3  # total upper triangles
    nv_l = len(tlx)         # total lower vertices
    nv_u = len(tux)         # total upper vertices
    ng = len(gx) // 3       # ground surface triangles

    # Element data
    element_offsets = []
    element_counts = []
    element_labels = []
    for region in regions:
        element_offsets.append(len(element_labels) + 1)
        labels = tuple(region.get("element_labels", ()))
        element_counts.append(len(labels))
        element_labels.extend(labels)
    if not element_labels:
        element_labels = [0]
    nelem = len(element_labels)

    fingerprint = plan["fingerprint"]
    lines = [
        "C=====================================================================",
        "C GENERATED BY GEOSTATIC INITIALIZER 3D. DO NOT EDIT TABLES.",
        "C MODEL: %s" % plan["model_name"],
        "C MODEL FINGERPRINT: %s" % fingerprint[:44],
        "C MODEL FINGERPRINT CONT: %s" % fingerprint[44:],
        "C INITIAL ACTIVE INSTANCES: %s"
        % ", ".join(region["instance"] for region in regions),
        "C COORDINATE CONVENTION: Z = VERTICAL UPWARD (+Z = TOWARD SURFACE)",
        "C=====================================================================",
        "",
        "C --- SIGINI: Initial stress field for 3D continuum ---",
        "      SUBROUTINE SIGINI(SIGMA,COORDS,NTENS,NCRDS,NOEL,NPT,",
        "     1 LAYER,KSPT,LFLAGS,NAMES)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      DIMENSION SIGMA(NTENS),COORDS(NCRDS),LFLAGS(2)",
        "      CHARACTER*80 NAMES(3),CPNAME",
        "      INTEGER I,IREG,LOCNUM,JRCD",
        "      DOUBLE PRECISION SV,K0,SXX,SYY,SZZ",
        "      DO I=1,NTENS",
        "         SIGMA(I)=0.D0",
        "      END DO",
        "      CALL GETPARTINFO(NOEL,1,CPNAME,LOCNUM,JRCD)",
        "      IF (JRCD.NE.0) CALL XIT",
        "      CALL KREGION(CPNAME,LOCNUM,IREG,JRCD)",
        "      IF (JRCD.NE.0) CALL XIT",
        "      CALL KSTRESS3(COORDS(1),COORDS(2),COORDS(3),IREG,SZZ,K0)",
        "      SXX=K0*SZZ",
        "      SYY=K0*SZZ",
        # 3D stress tensor (following Abaqus ordering):
        # S11=SXX, S22=SYY, S33=SZZ, S12=SXY, S13=SXZ, S23=SYZ
        # For geostatic: SZZ = vertical, SXX=SYY = K0*SZZ, shear = 0
        "      IF (NTENS.GE.1) SIGMA(1)=SXX",
        "      IF (NTENS.GE.2) SIGMA(2)=SYY",
        "      IF (NTENS.GE.3) SIGMA(3)=SZZ",
        "      IF (NTENS.GE.4) SIGMA(4)=0.D0",
        "      IF (NTENS.GE.5) SIGMA(5)=0.D0",
        "      IF (NTENS.GE.6) SIGMA(6)=0.D0",
        "      RETURN",
        "      END",
        "",
        "C --- UPOREP: Initial pore pressure for 3D ---",
        "      SUBROUTINE UPOREP(UW0,COORDS,NODE)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      DIMENSION COORDS(3)",
        "      DOUBLE PRECISION UW0,COORDS",
        "      CALL KPRESS3(COORDS(1),COORDS(2),COORDS(3),UW0)",
        "      RETURN",
        "      END",
        "",
        "C --- Region lookup (reused from 2D logic) ---",
    ]

    # KREGION (same as 2D)
    lines.extend([
        "      SUBROUTINE KREGION(CPNAME,LOCNUM,IREG,JRCD)",
        "      CHARACTER*80 CPNAME,INST(%d)" % nreg,
        "      INTEGER I,J,IREG,JRCD,LOCNUM",
        "      INTEGER IE(%d),NE(%d),ELABEL(%d)" % (nreg, nreg, nelem),
    ])
    lines.extend(_data_lines("INST", [r["instance"] for r in regions], _character))
    lines.extend(_data_lines("IE", element_offsets, _integer))
    lines.extend(_data_lines("NE", element_counts, _integer))
    lines.extend(_data_lines("ELABEL", element_labels, _integer))
    lines.extend([
        "      IREG=0",
        "      JRCD=1",
        "      DO I=1,%d" % nreg,
        "         IF (TRIM(CPNAME).EQ.TRIM(INST(I))) THEN",
        "            IF (NE(I).EQ.0) THEN",
        "               IREG=I",
        "               JRCD=0",
        "               RETURN",
        "            END IF",
        "            DO J=IE(I),IE(I)+NE(I)-1",
        "               IF (LOCNUM.EQ.ELABEL(J)) THEN",
        "                  IREG=I",
        "                  JRCD=0",
        "                  RETURN",
        "               END IF",
        "            END DO",
        "         END IF",
        "      END DO",
        "      RETURN",
        "      END",
        "",
    ])

    # KSTRESS3 - 3D vertical stress calculation
    nv_l_dim = max(nv_l, 1)
    nv_u_dim = max(nv_u, 1)
    lines.extend([
        "C --- 3D vertical stress by TIN interpolation ---",
        "      SUBROUTINE KSTRESS3(X,Y,Z,IREG,SZZ,K0OUT)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      INTEGER I,I0,IREG,J",
        "      INTEGER IL(%d),NL(%d),IU(%d),NU(%d)" % (nreg, nreg, nreg, nreg),
        "      INTEGER POROUS(%d)" % nreg,
        "      DOUBLE PRECISION X,Y,Z,SZZ,K0OUT,LOZ,UPZ,THICK,BULK,PW",
        "      DOUBLE PRECISION TLX(%d),TLY(%d),TLZ(%d)" % (nv_l_dim, nv_l_dim, nv_l_dim),
        "      DOUBLE PRECISION TUX(%d),TUY(%d),TUZ(%d)" % (nv_u_dim, nv_u_dim, nv_u_dim),
        "      DOUBLE PRECISION RHO(%d),POR(%d),SAT(%d),GW(%d)" % (nreg, nreg, nreg, nreg),
        "      DOUBLE PRECISION KZERO(%d)" % nreg,
    ])
    lines.extend(_data_lines("IL", ilo, _integer))
    lines.extend(_data_lines("NL", nlo, _integer))
    lines.extend(_data_lines("IU", iup, _integer))
    lines.extend(_data_lines("NU", nup, _integer))
    lines.extend(_data_lines("POROUS", [1 if r["porous"] else 0 for r in regions], _integer))
    lines.extend(_data_lines("TLX", tlx if tlx else [0.0]))
    lines.extend(_data_lines("TLY", tly if tly else [0.0]))
    lines.extend(_data_lines("TLZ", tlz if tlz else [0.0]))
    lines.extend(_data_lines("TUX", tux if tux else [0.0]))
    lines.extend(_data_lines("TUY", tuy if tuy else [0.0]))
    lines.extend(_data_lines("TUZ", tuz if tuz else [0.0]))
    lines.extend(_data_lines("RHO", [r["density"] for r in regions]))
    lines.extend(_data_lines("POR", [r["porosity"] for r in regions]))
    lines.extend(_data_lines("SAT", [r["saturation"] for r in regions]))
    lines.extend(_data_lines("GW", [r["specific_weight"] for r in regions]))
    lines.extend(_data_lines("KZERO", [r["k0"] for r in regions]))

    # KSTRESS3 body: loop over regions, interpolate upper/lower Z from TIN
    lines.extend([
        "      SZZ=0.D0",
        "      DO I=1,%d" % nreg,
        # Check if point is within this region's triangles (try lower surface)
        "         CALL KTINZ(X,Y,NL(I),TLX(IL(I)),TLY(IL(I)),TLZ(IL(I)),LOZ)",
        "         IF (LOZ.GT.1.D30) GO TO 100",
        "         CALL KTINZ(X,Y,NU(I),TUX(IU(I)),TUY(IU(I)),TUZ(IU(I)),UPZ)",
        "         IF (UPZ.GT.1.D30) GO TO 100",
        "         THICK=DMAX1(UPZ-DMAX1(Z,LOZ),0.D0)",
        "         BULK=RHO(I)*%s" % _d(plan["gravity"]),
        "         IF (POROUS(I).EQ.1) THEN",
        "            BULK=BULK+SAT(I)*POR(I)*GW(I)",
        "         END IF",
        "         SZZ=SZZ-BULK*THICK",
        "  100    CONTINUE",
        "      END DO",
        # Effective stress correction for porous return region
        "      IF (POROUS(IREG).EQ.1) THEN",
        "         CALL KPRESS3(X,Y,Z,PW)",
        "         SZZ=SZZ+SAT(IREG)*PW",
        "      END IF",
        "      K0OUT=KZERO(IREG)",
        "      RETURN",
        "      END",
        "",
    ])

    # KPRESS3 - 3D pore pressure
    ng_dim = max(ng, 1)
    lines.extend([
        "C --- 3D pore pressure ---",
        "      SUBROUTINE KPRESS3(X,Y,Z,PW)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      INTEGER NG",
        "      PARAMETER (NG=%d)" % ng_dim,
        "      DOUBLE PRECISION X,Y,Z,PW,ZS",
        "      DOUBLE PRECISION GX(NG),GY(NG),GZ(NG)",
    ])
    lines.extend(_data_lines("GX", gx if gx else [0.0]))
    lines.extend(_data_lines("GY", gy if gy else [0.0]))
    lines.extend(_data_lines("GZ", gz if gz else [0.0]))
    lines.extend([
        "      CALL KTINZ(X,Y,NG,GX,GY,GZ,ZS)",
        "      IF (ZS.GT.1.D30) THEN",
        "         PW=0.D0",
        "         RETURN",
        "      END IF",
        "      PW=%s*DMAX1(ZS-Z,0.D0)" % _d(plan["specific_weight"]),
        "      RETURN",
        "      END",
        "",
    ])

    # KTINZ - TIN interpolation subroutine
    lines.extend([
        "C --- TIN interpolation: (X,Y) -> Z in triangulated surface ---",
        "      SUBROUTINE KTINZ(X,Y,NT,XS,YS,ZS,ZOUT)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      INTEGER NT,I,I1,I2,I3",
        "      DOUBLE PRECISION X,Y,XS(*),YS(*),ZS(*),ZOUT",
        "      DOUBLE PRECISION DET,L1,L2,L3",
        "      DOUBLE PRECISION X1,Y1,Z1,X2,Y2,Z2,X3,Y3,Z3",
        "      DOUBLE PRECISION TINY",
        "      PARAMETER (TINY=1.D-12)",
        "      ZOUT=1.D31",
        "      IF (NT.LE.0) RETURN",
        "      DO I=1,NT",
        "         I1=(I-1)*3+1",
        "         I2=I1+1",
        "         I3=I1+2",
        "         X1=XS(I1); Y1=YS(I1); Z1=ZS(I1)",
        "         X2=XS(I2); Y2=YS(I2); Z2=ZS(I2)",
        "         X3=XS(I3); Y3=YS(I3); Z3=ZS(I3)",
        # Barycentric test in XY plane
        "         DET=(Y2-Y3)*(X1-X3)+(X3-X2)*(Y1-Y3)",
        "         IF (DABS(DET).LT.TINY) GO TO 200",
        "         L1=((Y2-Y3)*(X-X3)+(X3-X2)*(Y-Y3))/DET",
        "         L2=((Y3-Y1)*(X-X3)+(X1-X3)*(Y-Y3))/DET",
        "         L3=1.D0-L1-L2",
        "         IF (L1.GE.-TINY.AND.L2.GE.-TINY.AND.L3.GE.-TINY) THEN",
        "            ZOUT=L1*Z1+L2*Z2+L3*Z3",
        "            RETURN",
        "         END IF",
        "  200    CONTINUE",
        "      END DO",
        "      RETURN",
        "      END",
        "",
    ])

    return "\n".join(lines)


def render_project_python_3d(plan):
    """Generate project-local Python script for 3D."""
    return """from __future__ import print_function
import os
try:
    from geostatic_initializer_kernel import regenerate_project_pair_3d
except ImportError:
    from tools.abaqus_plugins.geostatic_initializer_2d.geostatic_initializer_kernel import regenerate_project_pair_3d

MODEL_NAME = {model!r}
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
FORTRAN_FILE = os.path.join(OUTPUT_DIR, 'initial_fields_generated_3d.for')

if __name__ == '__main__':
    result = regenerate_project_pair_3d(
        MODEL_NAME, OUTPUT_DIR, gravity={gravity!r}, k0={k0!r}
    )
    print(result)
""".format(
        model=plan["model_name"], gravity=plan["gravity"], k0=plan["regions"][0]["k0"]
    )


def _atomic_write(path, content, encoding="ascii"):
    temporary = path + ".tmp"
    with open(temporary, "w", encoding=encoding, newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, path)


def write_project_pair_3d(output_dir, plan, keep_backup=True):
    """Write 3D Fortran + Python files to output_dir."""
    output_dir = os.path.abspath(output_dir)
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir)
    fortran_path = os.path.join(output_dir, FORTRAN_NAME)
    python_path = os.path.join(output_dir, PYTHON_NAME)
    if keep_backup and os.path.isfile(fortran_path):
        shutil.copyfile(fortran_path, fortran_path + ".bak")
    _atomic_write(fortran_path, render_fortran_3d(plan), "ascii")
    _atomic_write(python_path, render_project_python_3d(plan), "utf-8")
    return {"fortran": fortran_path, "python": python_path}
