"""Render and write project-local SIGINI/UPOREP sources."""

from __future__ import division, print_function

import os
import shutil


FORTRAN_NAME = "initial_fields_generated.for"
PYTHON_NAME = "generate_geostatic_initial_fields.py"


def _d(value):
    return "%.12fD0" % float(value)


def _data_lines(name, values, formatter=_d):
    rendered = [formatter(value) for value in values]
    lines = ["      DATA %s /" % name]
    chunks = []
    current = []
    for value in rendered:
        candidate = current + [value]
        if current and len("     1 %s," % ",".join(candidate)) > 72:
            chunks.append(current)
            current = [value]
        else:
            current = candidate
        if len("     1 %s/" % value) > 72:
            raise ValueError("DATA item for %s exceeds fixed-format column 72" % name)
    if current:
        chunks.append(current)
    for index, chunk in enumerate(chunks):
        suffix = "/" if index + 1 == len(chunks) else ","
        lines.append("     1 %s%s" % (",".join(chunk), suffix))
    return lines


def _integer(value):
    return str(int(value))


def _character(value):
    return "'%s'" % str(value).upper().replace("'", "''")


def _flatten_profiles(plan):
    lower_offsets, lower_counts, lower_x, lower_y = [], [], [], []
    upper_offsets, upper_counts, upper_x, upper_y = [], [], [], []
    for region in plan["regions"]:
        lower_offsets.append(len(lower_x) + 1)
        lower_counts.append(len(region["lower"]))
        lower_x.extend(point[0] for point in region["lower"])
        lower_y.extend(point[1] for point in region["lower"])
        upper_offsets.append(len(upper_x) + 1)
        upper_counts.append(len(region["upper"]))
        upper_x.extend(point[0] for point in region["upper"])
        upper_y.extend(point[1] for point in region["upper"])
    return (
        lower_offsets, lower_counts, lower_x, lower_y,
        upper_offsets, upper_counts, upper_x, upper_y,
    )


def render_fortran(plan):
    regions = plan["regions"]
    for region in regions:
        if len(str(region["instance"]).upper()) > 60:
            raise ValueError("instance name exceeds fixed-format safe limit of 60 characters")
    ilo, nlo, xl, yl, iup, nup, xu, yu = _flatten_profiles(plan)
    nreg = len(regions)
    element_offsets = []
    element_counts = []
    element_labels = []
    for region in regions:
        element_offsets.append(len(element_labels) + 1)
        labels = tuple(region.get("element_labels", ()))
        element_counts.append(len(labels))
        element_labels.extend(labels)
    if not element_labels:
        element_labels = [0]
    nelem = len(element_labels)
    nlower = len(xl)
    nupper = len(xu)
    ground_x = [point[0] for point in plan["ground"]]
    ground_y = [point[1] for point in plan["ground"]]
    fingerprint = plan["fingerprint"]
    lines = [
        "C=====================================================================",
        "C GENERATED BY GEOSTATIC INITIALIZER 2D. DO NOT EDIT TABLES.",
        "C MODEL: %s" % plan["model_name"],
        "C MODEL FINGERPRINT: %s" % fingerprint[:44],
        "C MODEL FINGERPRINT CONT: %s" % fingerprint[44:],
        "C INITIAL ACTIVE INSTANCES: %s"
        % ", ".join(region["instance"] for region in regions),
        "C=====================================================================",
        "      SUBROUTINE SIGINI(SIGMA,COORDS,NTENS,NCRDS,NOEL,NPT,",
        "     1 LAYER,KSPT,LFLAGS,NAMES)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      DIMENSION SIGMA(NTENS),COORDS(NCRDS),LFLAGS(2)",
        "      CHARACTER*80 NAMES(3),CPNAME",
        "      INTEGER I,IREG,LOCNUM,JRCD",
        "      DOUBLE PRECISION SV,K0",
        "      DO I=1,NTENS",
        "         SIGMA(I)=0.D0",
        "      END DO",
        "      CALL GETPARTINFO(NOEL,1,CPNAME,LOCNUM,JRCD)",
        "      IF (JRCD.NE.0) CALL XIT",
        "      CALL KREGION(CPNAME,LOCNUM,IREG,JRCD)",
        "      IF (JRCD.NE.0) CALL XIT",
        "      CALL KSTRESS(COORDS(1),COORDS(2),IREG,SV,K0)",
        "      IF (NTENS.GE.1) SIGMA(1)=K0*SV",
        "      IF (NTENS.GE.2) SIGMA(2)=SV",
        "      IF (NTENS.GE.3) SIGMA(3)=K0*SV",
        "      RETURN",
        "      END",
        "C=====================================================================",
        "      SUBROUTINE UPOREP(UW0,COORDS,NODE)",
        "      INCLUDE 'ABA_PARAM.INC'",
        "      DIMENSION COORDS(3)",
        "      DOUBLE PRECISION UW0,COORDS",
        "      CALL KPRESS(COORDS(1),COORDS(2),UW0)",
        "      RETURN",
        "      END",
        "C=====================================================================",
        "      SUBROUTINE KREGION(CPNAME,LOCNUM,IREG,JRCD)",
        "      CHARACTER*80 CPNAME,INST(%d)" % nreg,
        "      INTEGER I,J,IREG,JRCD,LOCNUM",
        "      INTEGER IE(%d),NE(%d),ELABEL(%d)" % (nreg, nreg, nelem),
    ]
    lines.extend(_data_lines("INST", [r["instance"] for r in regions], _character))
    lines.extend(_data_lines("IE", element_offsets, _integer))
    lines.extend(_data_lines("NE", element_counts, _integer))
    lines.extend(_data_lines("ELABEL", element_labels, _integer))
    lines.extend(
        [
            "      IREG=0",
            "      JRCD=1",
            "      DO I=1,%d" % nreg,
            "         IF (TRIM(CPNAME).EQ.TRIM(INST(I))) THEN",
            "            IF (NE(I).EQ.0) THEN",
            "               IREG=I",
            "               JRCD=0",
            "               RETURN",
            "            END IF",
            "            DO J=IE(I),IE(I)+NE(I)-1",
            "               IF (LOCNUM.EQ.ELABEL(J)) THEN",
            "                  IREG=I",
            "                  JRCD=0",
            "                  RETURN",
            "               END IF",
            "            END DO",
            "         END IF",
            "      END DO",
            "      RETURN",
            "      END",
            "C=====================================================================",
            "      SUBROUTINE KSTRESS(X,Y,IREG,SV,K0OUT)",
            "      INCLUDE 'ABA_PARAM.INC'",
            "      INTEGER I,IREG,IL(%d),NL(%d),IU(%d),NU(%d)" % (nreg, nreg, nreg, nreg),
            "      INTEGER POROUS(%d)" % nreg,
            "      DOUBLE PRECISION X,Y,SV,K0OUT,LO,UP,THICK,BULK,PW",
            "      DOUBLE PRECISION XL(%d),YL(%d),XU(%d),YU(%d)"
            % (nlower, nlower, nupper, nupper),
            "      DOUBLE PRECISION RHO(%d),POR(%d),SAT(%d),GW(%d)"
            % (nreg, nreg, nreg, nreg),
            "      DOUBLE PRECISION KZERO(%d)" % nreg,
        ]
    )
    lines.extend(_data_lines("IL", ilo, _integer))
    lines.extend(_data_lines("NL", nlo, _integer))
    lines.extend(_data_lines("IU", iup, _integer))
    lines.extend(_data_lines("NU", nup, _integer))
    lines.extend(_data_lines("POROUS", [1 if r["porous"] else 0 for r in regions], _integer))
    lines.extend(_data_lines("XL", xl))
    lines.extend(_data_lines("YL", yl))
    lines.extend(_data_lines("XU", xu))
    lines.extend(_data_lines("YU", yu))
    lines.extend(_data_lines("RHO", [r["density"] for r in regions]))
    lines.extend(_data_lines("POR", [r["porosity"] for r in regions]))
    lines.extend(_data_lines("SAT", [r["saturation"] for r in regions]))
    lines.extend(_data_lines("GW", [r["specific_weight"] for r in regions]))
    lines.extend(_data_lines("KZERO", [r["k0"] for r in regions]))
    lines.extend(
        [
            "      SV=0.D0",
            "      DO I=1,%d" % nreg,
            "         IF (X.GE.XL(IL(I)).AND.",
            "     1       X.LE.XL(IL(I)+NL(I)-1)) THEN",
            "            CALL KINTERP(X,NL(I),XL(IL(I)),YL(IL(I)),LO)",
            "            CALL KINTERP(X,NU(I),XU(IU(I)),YU(IU(I)),UP)",
            "            THICK=DMAX1(UP-DMAX1(Y,LO),0.D0)",
            "            BULK=RHO(I)*%s" % _d(plan["gravity"]),
            "            IF (POROUS(I).EQ.1) THEN",
            "               BULK=BULK+SAT(I)*POR(I)*GW(I)",
            "            END IF",
            "            SV=SV-BULK*THICK",
            "         END IF",
            "      END DO",
            "      IF (POROUS(IREG).EQ.1) THEN",
            "         CALL KPRESS(X,Y,PW)",
            "         SV=SV+SAT(IREG)*PW",
            "      END IF",
            "      K0OUT=KZERO(IREG)",
            "      RETURN",
            "      END",
            "C=====================================================================",
            "      SUBROUTINE KPRESS(X,Y,PW)",
            "      INCLUDE 'ABA_PARAM.INC'",
            "      INTEGER NG",
            "      PARAMETER (NG=%d)" % len(ground_x),
            "      DOUBLE PRECISION X,Y,PW,YS,XG(NG),YG(NG)",
        ]
    )
    lines.extend(_data_lines("XG", ground_x))
    lines.extend(_data_lines("YG", ground_y))
    lines.extend(
        [
            "      CALL KINTERP(X,NG,XG,YG,YS)",
            "      PW=%s*DMAX1(YS-Y,0.D0)" % _d(plan["specific_weight"]),
            "      RETURN",
            "      END",
            "C=====================================================================",
            "      SUBROUTINE KINTERP(X,N,XS,YS,YVAL)",
            "      INCLUDE 'ABA_PARAM.INC'",
            "      INTEGER N,I",
            "      DOUBLE PRECISION X,XS(N),YS(N),YVAL,T",
            "      IF (X.LE.XS(1)) THEN",
            "         YVAL=YS(1)",
            "         RETURN",
            "      END IF",
            "      IF (X.GE.XS(N)) THEN",
            "         YVAL=YS(N)",
            "         RETURN",
            "      END IF",
            "      DO I=1,N-1",
            "         IF (X.GE.XS(I).AND.X.LE.XS(I+1)) THEN",
            "            T=(X-XS(I))/(XS(I+1)-XS(I))",
            "            YVAL=YS(I)+T*(YS(I+1)-YS(I))",
            "            RETURN",
            "         END IF",
            "      END DO",
            "      CALL XIT",
            "      END",
            "",
        ]
    )
    return "\n".join(lines)


def render_project_python(plan):
    return """from __future__ import print_function
import os
try:
    from geostatic_initializer_kernel import regenerate_project_pair
except ImportError:
    from tools.abaqus_plugins.geostatic_initializer_2d.geostatic_initializer_kernel import regenerate_project_pair

MODEL_NAME = {model!r}
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
FORTRAN_FILE = os.path.join(OUTPUT_DIR, 'initial_fields_generated.for')

if __name__ == '__main__':
    result = regenerate_project_pair(
        MODEL_NAME, OUTPUT_DIR, gravity={gravity!r}, k0={k0!r}
    )
    print(result)
""".format(
        model=plan["model_name"], gravity=plan["gravity"], k0=plan["regions"][0]["k0"]
    )


def _atomic_write(path, content, encoding):
    temporary = path + ".tmp"
    with open(temporary, "w", encoding=encoding, newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, path)


def write_project_pair(output_dir, plan, keep_backup=True):
    output_dir = os.path.abspath(output_dir)
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir)
    fortran_path = os.path.join(output_dir, FORTRAN_NAME)
    python_path = os.path.join(output_dir, PYTHON_NAME)
    if keep_backup and os.path.isfile(fortran_path):
        shutil.copyfile(fortran_path, fortran_path + ".bak")
    _atomic_write(fortran_path, render_fortran(plan), "ascii")
    _atomic_write(python_path, render_project_python(plan), "utf-8")
    return {"fortran": fortran_path, "python": python_path}
