"""Keyword-block generator for pre-computed geostatic initial conditions.

Writes *INITIAL CONDITIONS, TYPE=STRESS and TYPE=PORE PRESSURE directly
into the model keyword block, bypassing Fortran user subroutines entirely.
"""

from __future__ import division, print_function

import os
import shutil


# No separate Fortran file for pre-compute mode
PYTHON_NAME = "generate_geostatic_initial_fields_precompute.py"


def _d(value):
    return "%.6f" % float(value)


def render_keyword_blocks(plan, element_stresses, node_pore_pressures):
    """Generate keyword-block text for pre-computed stresses.

    plan:                the geostatic plan dict
    element_stresses:    {el_label: (S11,S22,S33,S12,S13,S23), ...}
    node_pore_pressures: {node_label: pore_pressure, ...}

    Returns a string suitable for insertion before the first *STEP.
    """
    lines = [
        "** GI2D BEGIN",
        "** Generated by Geostatic Initializer (Pre-compute method)",
        "** Model: %s" % plan.get("model_name", ""),
        "** Active instances: %s" % ", ".join(
            r["instance"] for r in plan.get("regions", ())
        ),
        "**",
        "** STRESS INITIAL CONDITIONS (per-element)",
    ]

    # Stress initial conditions
    # Format: *INITIAL CONDITIONS, TYPE=STRESS
    # element_label_or_set, S11, S22, S33, S12, S13, S23
    lines.append("*INITIAL CONDITIONS, TYPE=STRESS")
    for el_label in sorted(element_stresses):
        s11, s22, s33, s12, s13, s23 = element_stresses[el_label]
        lines.append(
            "%d, %s, %s, %s, %s, %s, %s"
            % (el_label, _d(s11), _d(s22), _d(s33), _d(s12), _d(s13), _d(s23))
        )

    # Pore pressure initial conditions (if coupled)
    if node_pore_pressures and "COUPLED" in plan.get("mode", ""):
        lines.append("**")
        lines.append("** PORE PRESSURE INITIAL CONDITIONS (per-node)")
        lines.append("*INITIAL CONDITIONS, TYPE=PORE PRESSURE")
        for nd_label in sorted(node_pore_pressures):
            pp = node_pore_pressures[nd_label]
            lines.append("%d, %s" % (nd_label, _d(pp)))

    lines.append("** GI2D END")
    lines.append("")
    return "\n".join(lines)


def render_project_python(plan):
    """Generate a project-local Python script for regeneration."""
    return """from __future__ import print_function
import os
try:
    from geostatic_initializer_kernel import regenerate_project_pair_precompute
except ImportError:
    from tools.abaqus_plugins.geostatic_initializer_2d.geostatic_initializer_kernel import regenerate_project_pair_precompute

MODEL_NAME = {model!r}
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

if __name__ == '__main__':
    result = regenerate_project_pair_precompute(
        MODEL_NAME, OUTPUT_DIR, gravity={gravity!r}, k0={k0!r}
    )
    print(result)
""".format(
        model=plan["model_name"],
        gravity=plan.get("gravity", 10.0),
        k0=plan.get("regions", ({},""))[0].get("k0", 1.0),
    )


def _atomic_write(path, content, encoding="ascii"):
    temporary = path + ".tmp"
    with open(temporary, "w", encoding=encoding, newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, path)


def write_project_pair_precompute(output_dir, plan, element_stresses, node_pore_pressures):
    """Write pre-computed keyword block and Python regeneration script."""
    output_dir = os.path.abspath(output_dir)
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir)
    keyword_path = os.path.join(output_dir, "initial_fields_generated_precompute.inp")
    python_path = os.path.join(output_dir, PYTHON_NAME)
    keyword_text = render_keyword_blocks(plan, element_stresses, node_pore_pressures)
    _atomic_write(keyword_path, keyword_text, "ascii")
    _atomic_write(python_path, render_project_python(plan), "utf-8")
    return {"keyword": keyword_path, "python": python_path}
